### ISSUE TITLE
How to Set Queue Expiration

### ISSUE THREAD

**Issue by despossivel** [hunterloftis/jackrabbit#115]
How to set Queue expiration? I don't see an example of how to pass the arguments in the queue or exchage

**Comment by despossivel** [comment]
I ended up figuring out how to pass arguments, and I believe this can be added to the documentation to make it easier for others

    exchange.queue({ name: 'NameQueue', durable: true, arguments:{'x-expires':420000} });

**Comment by despossivel** [comment]
added to the redm in that PR

https://github.com/hunterloftis/jackrabbit/pull/116

**Comment by matmar10** [comment]
Thanks for raising this and many thanks for contributing the new docs!
