### ISSUE TITLE
'expiration' is not documented / configurable.

### ISSUE THREAD

**Issue by stephengardner** [hunterloftis/jackrabbit#13]
On line 77 of queue.js there's an expiration for messages of 1 second.

This is a hugely confusing and problematic issue whereby messages will be lost when they don't complete in 1 second.  Why is this expiration in place?  Why is it not documented?  

If an asynchronous process does not ack() until the end of, for example, a long waiting API call, and there's only 1 worker, the worker just drops the message and the queue_length reflects this.  Am I missing something?

**Comment by Akamaozu** [comment]
You're not missing anything. 

Right now there's no way to configure the message expiry timer from jackrabbit's api. If your jobs don't finish within a second, the message expires and is lost.

There's a pull request that aims to fix this: https://github.com/hunterloftis/jackrabbit/pull/9.

As soon as Hunter pulls it, we'll be able to control the expiry timer.

**Comment by hunterloftis** [comment]
Excellent question, and fixed in #9 - should be good to go.

**Comment by stephengardner** [comment]
Thanks! From the pull diff, it looks like messageTtl will default to undefined which will mean a message never expires by default, correct?  I'd recommend documenting this feature, it doesn't seem readily obvious.  Thanks for the module
