### ISSUE TITLE
No support to nack() or reject messages?

### ISSUE THREAD

**Issue by stephengardner** [hunterloftis/jackrabbit#14]
In my understanding of amqp, there should be a way to nack() or reject messages.  These messages may then be processed by a different consumer at a later point in time.

If, for example, I'm queueing up messages to send emails, and at time of sending, the email API I'm using returns an unlikely error, I'd like to reject this message and try it again later.

How do I accomplish that with this module?

Thanks

**Comment by hunterloftis** [comment]
Good question - no way to at the moment! PRs welcome, but I'll keep this open for v4.0.0

**Comment by Akamaozu** [comment]
Pull request for a simple nack implementation here. 

https://github.com/hunterloftis/jackrabbit/pull/17

**Comment by hunterloftis** [comment]
Available in latest (`queue.consume(function(data, ack, nack, msg) { });`)

**Comment by naartjie** [comment]
@hunterloftis do you want a PR to document the above?

**Comment by hunterloftis** [comment]
@naartjie that'd be great!

**Comment by naartjie** [comment]
@hunterloftis here you go ;) #42
