### ISSUE TITLE
is this project/package still alive ?

### ISSUE THREAD

**Issue by maggiben** [hunterloftis/jackrabbit#15]
My company is using jackrabbit it in production, I noticed the lib it's using quite an outdated AMQP dependency, are there any plans on fixing that ? are contributors alive ?

**Comment by hunterloftis** [comment]
@maggiben happy to bump; PRs welcome but I can upgrade myself later this week.

**Comment by maggiben** [comment]
hunterloftis that's great ! I'll be working on this source for a few days, I've some free time if you need help.

**Comment by hunterloftis** [comment]
Awesome. Just merged some outstanding PRs; at the moment I'm trying to fit in the extended amqp options that folks have requested without bloating the API.
