### ISSUE TITLE
No Event/callback/promise to indicate when routingKeys have been bound to a queue.

### ISSUE THREAD

**Issue by ShurakaiSoft** [hunterloftis/jackrabbit#27]
While using `jackrabbit` and writing some tests, I came across an issue where I created a queue and started sending messages to it but those messages never arrived. After some digging it appears that when a queue is created `routingKeys` are bound but that call is asynchronous and it's possible that the queue reports `ready` before all routingKeys are correctly bound. There is no event/callback/promise to indicate when all `routingKeys` have been bound to the queue.

I have created a solution to this problem that raises a `bound` event to indicate when all routingKeys have been bound and the queue is ready to receive published messages. 

Link to the [PR](https://github.com/hunterloftis/jackrabbit/pull/26)

**Comment by hunterloftis** [comment]
Thank you @ShurakaiSoft for the find & for the fix! PR is merged in.
