### ISSUE TITLE
Ignore / purge queue 

### ISSUE THREAD

**Issue by JAertgeerts** [hunterloftis/jackrabbit#29]
I know this feature used to be available, but can't find how to. Is it just closing the queue?

**Comment by hunterloftis** [comment]
This is a big hole in the [queue API](https://github.com/hunterloftis/jackrabbit/blob/8d626155996f0b67d1076ce4069dcc731f97cfd7/lib/queue.js#L25-L30) right now. Can be implemented with [purgeQueue](http://www.squaremobius.net/amqp.node/channel_api.html#channel_purgeQueue).

**Comment by JAertgeerts** [comment]
Nice, thanks!
