### ISSUE TITLE
getting the size of the queue

### ISSUE THREAD

**Issue by matthewmueller** [hunterloftis/jackrabbit#41]
haven't dug too deep into the internals, but curious how difficult it would be to add support for checking the number of 'ready' and 'unacked' messages on the queue.

**Comment by matmar10** [comment]
This seems to be outside of the scope of this library given the design philosophy of incredible simplicity at the expense of limited features. 

For this type of feature, you probably could use something like the REST API built in to RabbitMQ admin, or similar.

See: https://pulse.mozilla.org/api/

Example:
https://yourserver.com/api/queues/vhost/queue-name

Then you can check `backing_queue_status.len`
