### ISSUE TITLE
Add example with PDF file transfer

### ISSUE THREAD

**Issue by amandapouget** [hunterloftis/jackrabbit#48]
Hi,

It would help immensely if you would post an example of Jackrabbit with client and server, where the client requests and eventually receives a PDF (vs. a "Hello World" string).

Trial and error to figure out the magical winning code is taking a long time and there's not much documented, so.... pretty please? ;-)

Amanda

**Comment by joshdickson40** [comment]
You probably just want to store the PDF somewhere and just send a message on where the consumer can download it from. It's technically possible to send large objects in RabbitMQ, but in practicality this is almost always the wrong way to implement what you're trying to do.
