### ISSUE TITLE
Reply queue is created even if opts.reply is set to false

### ISSUE THREAD

**Issue by danwkennedy** [hunterloftis/jackrabbit#53]
In lib/exchange.js, the sendMessage() method checks for opts.reply to interact with a replyQueue. However, when the exchange is created, the replyQueue is always created regardless of the value of opts.reply. This creates a bunch of un-named queues that we're not actually using (especially since a lot of our connections to an exchange are for listening to the queue instead of writing to it).

Could you check the opts and create the queue if necessary?

If that's an acceptable solution, I'd be willing to submit a PR for that check.

**Comment by matmar10** [comment]
Hi @danwkennedy - this seems like a completely reasonable solution. Could you create a PR for this?

**Comment by matmar10** [comment]
This should be fixed
