### ISSUE TITLE
messages not received after calling  .on('drain', rabbit.close)

### ISSUE THREAD

**Issue by mitchellporter** [hunterloftis/jackrabbit#55]
I have a singleton clock process that needs to publish some messages to workers once every 10 - 30 seconds.

Here's an example of my clock process publishing a job to a queue using jackrabbit: 

```
var exchange = rabbit.default();
exchange.queue({ name: MY_QUEUE_NAME, durable: true });
exchange.publish({ update_info: 'some data' }, { key: MY_QUEUE_NAME });
exchange.on('drain', rabbit.close);
```
My workers will receive the message the first time this code is ran, but anytime after that the messages are never received. If I delete `exchange.on('drain', rabbit.close)`, I will continue to receive messages even after the first one. This fixes the problem, but goes against the example shown in the `README`.

So, what is the correct behavior?

Thanks for the help.

**Comment by Akamaozu** [comment]
I believe `rabbit.close` ends the connection to rabbitmq, which explains why you aren't getting any more messages.

Basically you're disconnecting from rabbitmq when the exchange drains.

The correct behavior entirely depends on what you're trying to accomplish.

**Comment by mitchellporter** [comment]
Hey @Akamaozu thanks for the fast reply!

>The correct behavior entirely depends on what you're trying to accomplish.

Basically here's what I need.. I have multiple cron jobs that run every 10 to 30 seconds. I need to be able to send a message/job to my workers depending on which cron just fired. So here's an example of me creating my recurring cron jobs inside of my `clock.js`:

```
new CronJob('*/10 * * * * *', sortLiveFeed, null, true, 'America/Los_Angeles');
new CronJob('*/15 * * * * *', sortVODFeed, null, true, 'America/Los_Angeles');

```

The cron jobs above call these functions:

```
function sortLiveFeed() {
    
    // Publish message to queue
    var exchange = rabbit.default();
    exchange.queue({ name: SORT_LIVE_FEED_QUEUE, durable: true });
    exchange.publish({ status: 'live' }, { key: SORT_LIVE_FEED_QUEUE });
}
```

```
function sortVODFeed() {
    
    // Publish message to queue
    var exchange = rabbit.default();
    exchange.queue({ name: SORT_VOD_FEED_QUEUE, durable: true });
    exchange.publish({ status: 'vod' }, { key: SORT_VOD_FEED_QUEUE });
}
```

I basically just have a set of 10 different jobs that I will use throughout my entire app, and 4 of them happen to be created whenever their cron job fires. Above I showed you an example of 2 of these. 

I basically just want to be able to have my workers listen for and consume the jobs and handle them. Right now the above code works but like you saw in issue #56 that I started, this causes endless queues to be created.

I don't want endless queues to be created, I just want to create a queue for each job type, which I have 10 of, and that's it.

I'm not sure if that's the correct way to setup worker queues or not, I was just going off of the examples I could find for `jackrabbit`.

Thanks for the help.

**Comment by Akamaozu** [comment]
The code you posted seems like the correct way to do this. 

It basically says:

1. `var exchange = rabbit.default();`
- Create a new exchange. It's a default type.

2. `exchange.queue({ name: MY_QUEUE_NAME, durable: true });`
- Add a queue to the exchange. Call the queue the contents of `MY_QUEUE_NAME` variable. 
- Don't delete the queue even when there are no items on the queue. _(durable)_

3. `exchange.publish({ update_info: 'some data' }, { key: MY_QUEUE_NAME });`
- Send this object to this exchange.
- The routing key is the contents of `MY_QUEUE_NAME`, so send it to queues that match this name.

4. `exchange.on('drain', rabbit.close);`
- Close this connection when the exchange drains. _(I'm not sure what exchange drains really means .. I assume it means no more messages in the exchange, unqueued)_


Ps. 
All the workers you've posted create content, not process it.

**Comment by mitchellporter** [comment]
>All the workers you've posted create content, not process it.

Sorry, I have a feeling that I confused you by not describing the situation well enough. I want to make sure we both understand each other. I didn't post any worker code in this issue, only in the other issue I opened #56.

The code I provided in this comment above https://github.com/hunterloftis/jackrabbit/issues/55#issuecomment-251820586 only shows jobs / messages being created, not workers receiving messages and handling jobs.

Now that I've said all of this, would you still say `All the workers you've posted create content, not process it.`? I want to make sure that my code above for publishing messages is correct and that we're understanding each other correctly :)
