### ISSUE TITLE
TypeError: Cannot read property 'publish' of undefined

### ISSUE THREAD

**Issue by mitchellporter** [hunterloftis/jackrabbit#60]
I first noticed this error and it has since been happening every few hours on one of my servers. I don't think I have ever experience this before, but it could be that this is just the first time I have noticed.

For some reason I am getting an exception of `TypeError: Cannot read property 'publish' of undefined`

This error will happen after the server has been running fine for a few hours. Once it happens, several server restarts will fail as this error keeps happening. Eventually the server will try to restart again and eventually this error will stop happening.

I don't know what is causing this or how to fix it, especially since it seems to happen randomly and doesn't throw an error all the time.

Below is the stack trace. I have removed the timestamps for easier reading.

```
 /app/node_modules/jackrabbit/lib/exchange.js:128
app[clock.1]:       var drained = channel.publish(emitter.name, opts.key, new Buffer(msg), opts);
app[clock.1]:                            ^
app[clock.1]: 
app[clock.1]: TypeError: Cannot read property 'publish' of undefined
app[clock.1]:     at sendMessage (/app/node_modules/jackrabbit/lib/exchange.js:128:28)
app[clock.1]:     at EventEmitter.publish (/app/node_modules/jackrabbit/lib/exchange.js:114:16)
app[clock.1]:     at CronJob.sortLiveBroadcasts (/app/lib/clock.js:38:14)
app[clock.1]:     at CronJob.fireOnTick (/app/node_modules/cron/lib/cron.js:392:22)
app[clock.1]:     at Timeout.callbackWrapper [as _onTimeout] (/app/node_modules/cron/lib/cron.js:435:9)
app[clock.1]:     at tryOnTimeout (timers.js:224:11)
app[clock.1]:     at Timer.listOnTimeout (timers.js:198:5)
```

Here is the code for my entire `clock.js` file:

```
var config = require('./server/config/config');
var logger = require('./logger');
var CronJob = require('cron').CronJob;
var rabbit = require('jackrabbit')(config.rabbit_url);
var exchange = rabbit.default();

var SORT_LIVE_FEED_QUEUE = config.SORT_LIVE_FEED_QUEUE;
var SORT_VOD_FEED_QUEUE = config.SORT_VOD_FEED_QUEUE;

var sortLiveBroadcastsJob = new CronJob('*/10 * * * * *', sortLiveBroadcasts, null, false, 'America/Los_Angeles');
var sortVODBroadcastsJob = new CronJob('*/15 * * * * *', sortVODBroadcasts, null, false, 'America/Los_Angeles');

sortLiveBroadcastsJob.start();
sortVODBroadcastsJob.start();

// Graceful shutdown
var gracefulShutdown = function() {
    sortLiveBroadcastsJob.stop();
    sortVODBroadcastsJob.stop();
    rabbit.close();
}

process.on('SIGTERM', gracefulShutdown);

function sortLiveBroadcasts() {

    // Publish message to queue
    exchange.queue({ name: SORT_LIVE_FEED_QUEUE, durable: true });
    exchange.publish({ status: 'live' }, { key: SORT_LIVE_FEED_QUEUE });
}

function sortVODBroadcasts() {

    // Publish message to queue
    exchange.queue({ name: SORT_VOD_FEED_QUEUE, durable: true });
    exchange.publish({ status: 'vod' }, { key: SORT_VOD_FEED_QUEUE });
}
```

**Comment by mitchellporter** [comment]
Just an update, after playing around with this some more... this is now guaranteed to happen within 20 minutes of starting my server.

**Comment by mitchellporter** [comment]
Another update... this error will happen every hour or so. When the server auto-restarts, most of the time it will work just fine but sometimes it will experience the same error several times in a row.

**Comment by mitchellporter** [comment]
Ok so I watched this very closely and here are the final results: The above error appears every 20 minutes exactly. The error is thrown, the server crashes, auto restarts, and then runs fine for another 20 minutes. This has been happening since I first opened this issue.

**Comment by newhouse** [comment]
@mitchellporter I'm experiencing this same issue. What was your solution?

**Comment by mitchellporter** [comment]
@newhouse Unfortunately I never solved it and then moved on to another project. I would suggest choosing a different package that is actually maintained. Good luck!

**Comment by boopathi782** [comment]
i got the same issue for if hit 2000 request with for loop from angular appliction, i get this error at 1021th request until before it working fine for 1000 request,  any solution please below is my code 

app.get('/publish_data', function(req, res) {
    msgQueue = exchange.queue({name: topic, durable: true});
    var message = req.query.message;
   // console.log('Message sent is: ' + message);
    exchange.publish({msg:message}, {key: topic});    
    // recevies message // consumer consume message  // /* like receiver */
        msgQueue = exchange.queue({name: '#', durable: true});
        msgQueue.consume(sendMsg);
        return res.json({ message: "Welcome to node application. rquest reply no:  "+ message });        
});
