### ISSUE TITLE
Appear to be missing subscribe/handle callbacks

### ISSUE THREAD

**Issue by afreeland** [hunterloftis/jackrabbit#7]
When I publish a single message at a time to rabbitmq my handle callback appears to work 100%.  However I wanted to test the throughput, so I created an api route that simply iterates over 50, and calls queue.publish with the current iteration index.  

I am not sure that queue.publish is actually publishing all 50...or if the handle callback is simply not getting called 50 times.  Typically we have C# engines that process rabbitmq messages but using JavaScript all the way through would make the most sense...does this look correct?

```
// RabbitMQ url
var url = 'amqp://rabbitmq-01';

// Connect to RabbitMQ
var queue = jackrabbit(url);

// When connected
queue.on('connected', function () {
	
	// Create a queue, create(name, options, callback, func)
	queue.create('nodeTest', { prefetch: 1 }, onReady);

	function onReady () {
		// Start handling jobs in 'nodeTest'
		queue.handle('nodeTest', onJob);

		// Publish a job to queue
		queue.publish('nodeTest', { name: 'test'});
	}

	function onJob (job, ack) {
		console.log('Hello ' + job.name);
		ack();
	}
});

app.get('/test', function (req, res) {

	function publishMessage (i) {
		queue.publish('nodeTest', { name: 'iteration ' + i });
		console.log('published ' + i);
	}
	for (var i = 0; i < 50; i++) {
		(publishMessage)(i);
	}
	
	res.send('published');
});
```

**Comment by naneer** [comment]
+1, similar issue as well.  I ended removing the `expiration:'1000'` from the sendToQueue call in Queue.prototype.publish.  But I am curious to see if there's a better way or a reason not to do this, I just started learning rabbitmq.  Any advice much appreciated!

In queue.js
```
Queue.prototype.publish = function(obj, replyHandler) {
  var msg = JSON.stringify(obj);
  var id = uuid.v4();
  if (replyHandler) {
    this.channel.replyHandlers[id] = replyHandler;
  }
  this.channel.sendToQueue(this.name, new Buffer(msg), {
    persistent: !replyHandler,
    correlationId: id,
    expiration: '1000', <---- I removed this
    replyTo: replyHandler ? this.channel.replyName : undefined
  });
};
```

**Comment by hunterloftis** [comment]
Sorry for leaving you hanging; closing for now, please reopen if this is still outstanding!
