### ISSUE TITLE
Heroku: MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by dmorrow** [hunterloftis/jackrabbit#73]
I am getting the following error on Heroku
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit`

The code that I believe is triggering it is relatively simple:

    const rabbit = jackrabbit(constants.RABBITURL);
    const exchange = rabbit.default();
    exchange
    .queue({ name: constants.videoProcess })
    .consume(filterVideo, { noAck: true });

    exchange
    .queue({ name: constants.imageProcess })
    .consume(filterImage, { noAck: true });`

**Comment by tao** [comment]
You can add this to your `index.js` file before any code runs, I don't believe it's related to this project exactly, perhaps a rabbitmq issue.

```js
/**
 * Increase the max event listeners on a global scale
 * to prevent this error.
 *
 * MaxListenersExceededWarning:
 * Possible EventEmitter memory leak detected.
 * Use emitter.setMaxListeners() to increase limit
 */
require('events').EventEmitter.prototype._maxListeners = 25;
```

**Comment by matmar10** [comment]
Closing since not specific to this repo.
