### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by JAertgeerts** [hunterloftis/jackrabbit#74]
Looking at the open PR’s waiting for a merge - @hunterloftis are you still interested in maintaining this library? If not, it’d be great if the community could take ownership.

**Comment by tao** [comment]
This version seems to be the one that's updated the most [@pagerinc/jackrabbit](https://github.com/pagerinc/jackrabbit) so I've been using that for my projects.

**Comment by hunterloftis** [comment]
https://github.com/hunterloftis/jackrabbit/issues/77

**Comment by matmar10** [comment]
Closing - I'll be going through the backlog and doing some issue maintenance. @JAertgeerts olease comment on #77 if you'd like to be added as a contributor as well. 

@tao will add a task to sync with @pagerinc/jackrabbit (will santity check first) since you've noted that it is more up to date.
