### ISSUE TITLE
Jackrabbit needs a new owner!

### ISSUE THREAD

**Issue by hunterloftis** [hunterloftis/jackrabbit#77]
Or owners.

I've neglected this project for too long with intentions to release a "next big version" from some of the development branches I have sitting locally. But as many of you have noticed, I haven't actually shipped anything, and that's not fair to people who are depending on this.

**In order to stop blocking the community, I'd like to give owner access both on Github and on npm to other developers who have been actively working on Jackrabbit.** If that person should be you, please comment here so I know who is interested, available, and capable.

Thank you!

**Comment by Akamaozu** [comment]
Hope the newest owner has the same desire to keep the api as simple as @hunterloftis has.

**Comment by matmar10** [comment]
@hunterloftis I've only made one notable contribution (yet unmerged) but I'm willing to take this up. Since we're using it for several active projects, we can give it institutional support with a bit of dedicated time to bring it up to date and process the backlog of PRs.

Agreed with @Akamaozu - part of the reason I/we love this lib is it's made super simple by design.

**Comment by hunterloftis** [comment]
Thanks for volunteering @matmar10 - I just collab'd you on both GH and npm. Please be sure to follow semver so nobody gets an unexpected patch version bump.

**Comment by matmar10** [comment]
Excellent. Happy to help out and keep this great library alive.

**Comment by Akamaozu** [comment]
Agree with @matmar10.

This library made it easy to get started with RabbitMQ, which has been invaluable to me. If there's anything I can do to help, please let me know :)

**Comment by JAertgeerts** [comment]
I’d be happy to take up any issues!

**Comment by matmar10** [comment]
@JAertgeerts awesome! It looks like something broke with CI on Travis. Can you check out the build there and take a stab at fixing it? That would help expedite my process of working through the issue backlog and mergability of contributions.

**Comment by JAertgeerts** [comment]
@matmar10 Apologies for the bucket load of commits, but #79 fixes #36
