### ISSUE TITLE
New Version on npm

### ISSUE THREAD

**Issue by DooMachine** [hunterloftis/jackrabbit#97]
Version 4.3.0 uses Promise.defer and it is last version on npm, so it needs to be updated to prevent some future errors.

**Comment by Akamaozu** [comment]
Second this issue. 

Jackrabbit is busted for me and I can't bind queues to exchanges because of this.

@matmar10 can you please help push the new version up?

**Comment by Akamaozu** [comment]
or maybe @hunterloftis?

Should still have credentials to push the latest version up.

**Comment by matmar10** [comment]
Sure I can push a version tomorrow.

For some reason I thought I'd already cut a new tag for the latest.

**Comment by matmar10** [comment]
Done - Version 4.4.0 is live in NPM.  For some reason the publish script didn't push to npm .. I think maybe I wasn't logged in or something when I cut the release.
